// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4yQA8Pmg28Wl4LhkWE7A7mXGzXvZfgM',
    appId: '1:673059532182:web:4712c52c0d596356d6c1b7',
    messagingSenderId: '673059532182',
    projectId: 'medisafe-8dfae',
    authDomain: 'medisafe-8dfae.firebaseapp.com',
    storageBucket: 'medisafe-8dfae.firebasestorage.app',
    measurementId: 'G-PC7GXRWCMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNzQUk3Tk7GtN-6zCtfaajJl17-8N8SjA',
    appId: '1:673059532182:android:b92c2f68a385dbe4d6c1b7',
    messagingSenderId: '673059532182',
    projectId: 'medisafe-8dfae',
    storageBucket: 'medisafe-8dfae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4xbuk-K9IeQWflYdckUERmwfY7ggVmo',
    appId: '1:673059532182:ios:a0bf87b95140e9d9d6c1b7',
    messagingSenderId: '673059532182',
    projectId: 'medisafe-8dfae',
    storageBucket: 'medisafe-8dfae.firebasestorage.app',
    iosBundleId: 'com.example.medisafe',
  );
}
